<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>verifikasi field Firstname Kosong</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>33d8ffb0-58eb-4758-be85-0b3955822e2d</testSuiteGuid>
   <testCaseLink>
      <guid>9d6ab9bb-7532-46e5-8889-074aa459dd55</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Positive/Verifikasi login berhasil</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a00b4519-6140-404d-9262-1d426dfdb1e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7c7ad25-3859-4b6c-a51b-3454ebdf1110</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>345f5295-b650-43b6-bcda-4e5f9edba4bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PIM/Negative/Verifikasi field First Name Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f498a44c-ab77-4143-94df-962afa4beb75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5741574f-ca19-4ea2-811c-e9d6f6651ad2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5344aa91-e9b0-4360-880d-fd545d5f37ca</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
